# 核心仓库配置
owner: BYWled
repo: wled-status

secrets:
  - CF_WAF_TOKEN

# 待监测的站点
sites:
  - name: 🌐 官网
    url: https://www.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 🌐 官网 (镜像)
    url: https://mirror.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 📝 博客
    url: https://blog.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 📝 博客 (镜像)
    url: https://mirror-blog.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 🛒 乐购商城
    url: https://store.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 🛒 乐购商城 (镜像)
    url: https://mirror-store.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 🛠️ 后台管理系统
    url: https://admin.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 🛠️ 后台管理系统 (镜像)
    url: https://mirror-admin.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 🔬 光谱平台
    url: https://score.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 🔬 光谱平台 (镜像)
    url: https://mirror-score.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 📺 数字大屏
    url: https://city.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"

  - name: 📊 状态监控
    url: https://status.wled.top
    headers:
      - "X-Upptime-Token: $CF_WAF_TOKEN"
  - name: 📊 状态监控 (本站)
    url: https://mirror-status.wled.top

# GitHub Pages 状态页展现设置
status-website:
  cname: mirror-status.wled.top
  logoUrl: https://blog.wled.top/images/Wled-avatar.svg
  baseUrl: /
  title: BYWled服务状态面板
  navbar:
    - title: 状态监控
      href: /
    - title: GitHub 主页
      href: https://github.com/BYWled
